baseurl: "https://rucer.netlify.app/"
title: 人大国新班 2016 级
theme: ghostwriter
languageCode: en-us
copyright:  国际新闻课程作业
disqusShortname: XXX
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true
enableEmoji: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: 国际新闻课程作业
  profile: "https://google.com/+XXX"

taxonomies:
  category: categories
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: RUC
  description: School of Journalism and Mass Communication
  github: ""
  gitlab: "" 
  linkedin: "https://linkedin.com/in/michaeljjordan23/"
  twitter: "https://twitter.com/mjjordanink"
  stackoverflow: ""
  facebook: ""
  email: mjjordan2016@yahoo.com
  opengraph: true
  shareTwitter: true
  shareFacebook: true
  shareGooglePlus: false
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  GithubEdit: "https://github.com/hongtaoh/guoxinban/edit/master/content/"
  
permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Students' Work
      url: /
      weight: 1
    - name: Assignments
      url: /assignment/
      weight: 2
    - name: People
      url: /page/people/
      weight: 3
    - name: About the Course
      url: /page/about/
      weight: 4
    - name: Lesson Shared
      url: /page/lessonshared/
      weight: 5
    - name: Lesson Learned
      url: /page/lessonlearned/
      weight: 6
